---
title: "tidy_data"
author: "Courtney Johnson"
date: "September 25, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```
```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()
pulse_data
```

This isn't tidy yet...

```{r}
pulse_tidy = pulse_data %>%
  gather(key = "visit", value = "bdi score", bdi_score_bl:bdi_score_12m)
```

Illustrate separate:


```{r}
pulse_tidy %>%
  separate(visit, into = c("bdi_str", "score_str", "visit"), sep = "_") %>%
  select(-bdi_str, -score_str) %>%
  mutate(visit = replace(visit, visit == "bl", "00m"))
```

Altogether the data import/ cleaning pipeline is

```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>%
  gather(key = "visit", value = "bdi score", bdi_score_bl:bdi_score_12m) %>%
  separate(visit, into = c("bdi_str", "score_str", "visit"), sep = "_") %>%
  select(-bdi_str, -score_str) %>%
  mutate(visit = replace(visit, visit == "bl", "00m"))
```

## Revisit FAS_litters

```{r}
litters_data = read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  separate(group, into = c("dose", "day"), 3) 
```

## Learning Assessment

Write a chain that retains only litter_number, gd0_weight and gd18_weight; makes gd a numeric variable with values 0 and 18

```{r}
litters_data_assessment = read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(litter_number, ends_with("weight")) %>%
  gather(key = "gest_day", value = "weight", gd0_weight:gd18_weight) %>%
  mutate(gest_day = recode(gest_day, "gd0_weight" = 0, "gd18_weight" = 18)) %>%
  arrange(litter_number) 
```

```{r}
analysis_result = tibble(
  group = c("treatment", "treatment", "placebo", "placebo"),
  time = c("pre", "post", "pre", "post"),
  mean = c(4, 8, 3.5, 4)
)
```

Make it readable

```{r}
analysis_result %>%
  spread(key = time, value = mean) %>%
  knitr::kable()
```



